// const data :{
//     additionalLocationIdentificationDp:"",
//       sublocationIdentificationDp:"",
//       locationNameDp:"",
//       locationSpecificInstructionsDp:"",
//       uTCOffsetDp:"",
//       cityNameDp:"",
//       countryDp:"",
//       crossStreetDp:"",
//       currencyOfPartyDp:"",
//       launguageOfthePartyDp:"",
//       nameDp:"",
//       postBoxNumberDp:"",
//       postalCodeDp:"",
//       provinceDp:"",
//       stateDp:"",
//       streetAddressOneDp:"",
//       streetAddressTwoDp:"",
//       streetAddressThreeDp:"",
//       latitudeDp:"",
//       longitutueDp:"",

//       contactTypeDp:"",
//       personeNameDp:"",
//       depormentNameDp:"",
//       jobTitleDp:"",
//       responsibilityDp:"",
//       communicationChannelCodeDp:"",
//       communicationValueDp:"",
//       communicationChannelNameDp:""


// }



/// DropOffLocation
// additionalLocationIdentificationDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.additionalLocationIdentification.Name,
// sublocationIdentificationDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.sublocationIdentification,
// locationNameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.locationName,
// locationSpecificInstructionsDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.locationSpecificInstructions.Name,
// uTCOffsetDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.UtcOffSet,
// cityNameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.City,
// countryDp:TcbData &&  TcbData.data.plannedDropOff.Logisticlocation.countryCode.Name,
// crossStreetDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.crossStreet,
// currencyOfPartyDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.currencyOfParty.Name,
// launguageOfthePartyDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.languageOfTheParty.Name,
// nameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.name,
// postBoxNumberDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.pOBoxNumber,
// postalCodeDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.postalCode,
// provinceDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.province,
// stateDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.state,
// streetAddressOneDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.streetAddressOne,
// streetAddressTwoDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.streetAddressTwo,
// streetAddressThreeDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.streetAddressThree,
// latitudeDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.latitude,
// longitutueDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.longitude,

// contactTypeDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.contact,
// personeNameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.personeName,
// depormentNameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.depormentName,
// jobTitleDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.jobTitle,
// // responsibilityDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.responsibility.Name,
// responsibilityDp:'',
// // communicationChannelCodeDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.communicationChannelCode.Name,
// communicationChannelCodeDp:'',
// communicationValueDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.communicationValue,
// communicationChannelNameDp:TcbData && TcbData.data.plannedDropOff.Logisticlocation.communicationChannelName


const initialValues = {
  cargoType :'',
  harmonizedSystemCode: "", 
  cargoTypeDescription: "", 
  countryOfOriginCode: "", 
  finalDestinationCountry: "",
  totalGrossVolume:'',
  totalGrossVolumeCodes:"",
  totalGrossWeight: '',
  totalGrossWeightCodes:'',
  totalTransportNetWeight: "",
  totalTransportNetWeightCodes:"",
  totalChargeableWeight: "",
  totalChargeableWeightCodes: "",
  declaredWeightForCustoms: "", 
  declaredWeightForCustomsCodes: "", 
  totalLoadingLength: "", 
  totalLoadingLengthCodes: "",
  associatedInvoiceAmount: "",
  associatedInvoiceAmountCodes: "",
  declaredValueForCustoms: "", 
  declaredValueForCustomsCodes:"",
  totalPackageQuantity: "",
  totalPackageQuantityCodes: "",
  totalItemQuantity: "", 
  totalItemQuantityCodes: "", 
  packageTypeCode: "",
  totalPackageQuantityPT:"",
  totalGrossWeightPT:"",
  totalGrossWeightPTCodes:"",
  totalGrossVolumePT:"",
  totalGrossVolumePTCodes:"",  
}